-- Target list for cf1k10k

-- you can get histogram of top targets with this tool in apps/test
-- example: th test-dataset-dir.lua --datadir ~/Desktop/person-body/ -m cf1k10k --pdt 0.006


local targets = {
   ['cat'] = {
      'cat',
      --'dog',
      'fur',
      'haired',
      --'labrador',
      'medium',
      --'puppy',
      'sized',
      'tabby',
      'tiger',
   },
   ['dog'] = {
      'bull',
      'dog',
      'fur',
      'golden',
      'haired',
      'labrador',
      'medium',
      'puppy',
      'sized',
      'small',
   },
   ['pet'] = {
      'cat',
      --'dog',
      'fur',
      'haired',
      --'labrador',
      'medium',
      --'puppy',
      'sized',
      'tabby',
      'tiger',
      'bull',
      'dog',
      'fur',
      'golden',
      'haired',
      'labrador',
      'medium',
      'puppy',
      'sized',
      'small',
   },
   ['person'] = {
      'baby',
      'boy',
      'boys',
      'bra',
      'cardigan',
      'child',
      'children',
      'coat',
      'coat',
      'collared',
      'face',
      'female',
      'figure',
      'girl',
      'girls',
      'hand',
      'hooded',
      'human',
      'jacket',
      'khaki',
      'kid',
      'kids',
      'male',
      'man',
      'mans',
      'men',
      'mens',
      'people',
      'person',
      'person',
      'persons',
      'persons',
      'sleeve',
      'sleeveless',
      'smiling',
      'standing',
      'statue',
      'suit',
      'uniform',
      'vest',
      'woman',
      'womans',
      'women',
      'womens',
      'zip',
   },
}

return targets
